import "./globals.css";

export const metadata = {
  title: " Nextjs Approuter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="min-h-screen">{children}</div>
    </html>
  );
}
